name: Build & Install Jayanth's Gexu
on:
  workflow_dispatch:  # This adds the manual "Run" button
  push:
    branches:
      - main

jobs:
  build:
    name: Build Gexu Debug APK
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Standard Debug APK
        run: ./gradlew :app:assembleStandardDebug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Gexu-Jay-Debug-Build
          path: app/build/outputs/apk/standard/debug/*.apk
